# vars must be defined to be used
# format:
# key: ${ENV_VAR}
# key: ${ENV_VAR-:default}
# and "%{key}" can be used for settings values if available
variables:
  node_name_prefix: ${NODE_NAME_PREFIX:-node}
  node_hostname_prefix: ${NODE_HOSTNAME_PREFIX:-node}
  node_domain_affix: ${NODE_DOMAIN_AFFIX:-local}
  # some_value: ${MY_VAR:-value}-affix



# vagrant related settings
vagrant:
  # vagrant plugins are actually rubygems so you can declare to use any rubygems
  # common config level
  plugins: []
    # - _id: "0"
    #   name: vagrant-gatling-rsync
    #   version: "" # empty means latest by default
    #   state: installed # uninstalled
    #   enabled: true
    #   config_key: gatling
    #   options:
    #     latency: 0.5
    #     time_format: "%H:%M:%S"
    #     rsync_on_startup: true


# default settings for all nodes
default:
  vm:
    box: bento/ubuntu-16.04
    box_version:
    box_url:
    synced_folders: []

  providers:
    - _id: "0"
      enabled: true
      type: virtualbox
      require_version: ">=5.2.14"
      gui: false
      memory: 1024
      description: "%{node_name_prefix} #{Time.now.getutc.to_i}"

  provisioners: []

  # default node config level
  plugins: []

# specific nodes, each node will override the default
nodes:
  - _id: "0"
    name: "%{node_name_prefix}-01"
    primary: true
    vm:
      hostname: "%{node_hostname_prefix}-01.%{node_domain_affix}"
